#!/usr/bin/env ts-node

import * as ejs from 'ejs';
import * as fs from 'fs';
import * as DATA from './helpers/prepare-readme-data';
import * as path from 'path';

const templateFile = 'content/README.ejs';
const outputFile = 'README.md';
const TEMPLATE_PATH = path.resolve(__dirname, `../../${templateFile}`);
const OUTPUT_PATH = path.resolve(__dirname, `../../${outputFile}`);

(async function () {
  console.log(`\nBuilding: ${templateFile} -> ${outputFile}`);
  const output: string = await ejs.renderFile(TEMPLATE_PATH, {
    ...DATA,
    DONT_EDIT_WARNING: `! DO NOT EDIT THIS FILE. IT IS AUTOGENERATED.\nTo edit this file, edit its template in \`${path
      .relative(path.dirname(OUTPUT_PATH), TEMPLATE_PATH)
      .replace(/\\/g, '/')}\`.`
  });
  fs.writeFileSync(OUTPUT_PATH, output);
})();
