const ejs = require('ejs');
const fs = require('fs-extra');
const path = require('path');
const DATA = require('./prepare-data');
const { getAllFilesInTree } = require('../helpers');

const TEMPLATES_PATH = path.resolve(__dirname, '../../content/templates');
const OUTPUT_PATH = path.resolve(__dirname, '../../');

const templates = getAllFilesInTree(TEMPLATES_PATH)
  .map(file => path.relative(TEMPLATES_PATH, file))
  .filter(file => file.endsWith('.ejs'));
templates.forEach(async template => {
  console.log(`Building ${template}`);
  const templatePath = path.resolve(TEMPLATES_PATH, template);
  const outputPath = path.resolve(OUTPUT_PATH, template.replace(/\.ejs$/, ''));
  const output = await ejs.renderFile(templatePath, {
    ...DATA,
    DONT_EDIT_WARNING: `! DO NOT EDIT THIS FILE. IT IS AUTOGENERATED.\nTo edit this file, make an edit to its template in \`${path
      .relative(path.dirname(outputPath), templatePath)
      .replace(/\\/g, '/')}\`.`
  });
  fs.ensureDirSync(path.dirname(outputPath));
  fs.writeFileSync(outputPath, output);
});
