#!/usr/bin/env ts-node
import * as ejs from 'ejs';
import * as fs from 'fs';
import * as DATA from './helpers/prepare-data';
import * as path from 'path';

const TEMPLATE_PATH = path.resolve(__dirname, '../../content/README.ejs');
const OUTPUT_PATH = path.resolve(__dirname, '../../README.md');

(async function () {
  console.log(`Building ${TEMPLATE_PATH}`);
  const output: string = await ejs.renderFile(TEMPLATE_PATH, {
    ...DATA,
    DONT_EDIT_WARNING: `! DO NOT EDIT THIS FILE. IT IS AUTOGENERATED.\nTo edit this file, make an edit to its template in \`${path
      .relative(path.dirname(OUTPUT_PATH), TEMPLATE_PATH)
      .replace(/\\/g, '/')}\`.`
  });
  fs.writeFileSync(OUTPUT_PATH, output);
})();
