name: ⚡ Build ejs templates
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - name: Build and commit changes
        run: |
          yarn build content --skip-nx-cache
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "docs: :memo: build content (ejs templates)" || true
          git push
